name: DamageDisplay
main: com.gmail.bobason01.DamageDisplay
version: 1.0
author: crston
api-version: 1.21
description: Custom Font Damage Indicator
depend:
  - MythicMobs
commands:
  setdamageskin:
    description: Changes the damage skin
    usage: /setdamageskin <number>
  damagereload:
    description: Reloads the plugin configuration
    usage: /damagereload
permissions:
  damagedisplay.reload:
    description: Reload the plugin configuration
    default: op