name: DamageDisplay
version: 1.0.0
main: com.gmail.bobason01.DamageDisplay
api-version: 1.19
author: crston
commands:
  damagedisplay:
    description: Main command for DamageDisplay
    usage: /<command> <reload|set|blacklist>
    aliases: [dd]
    permission: damagedisplay.use
permissions:
  damagedisplay.skin.*:
    description: All skins
    default: op