name: DamageDisplay
version: 3.0
main: com.gmail.bobason01.DamageDisplay
api-version: 1.19
author: crston
depend: [MythicMobs, ProtocolLib]
commands:
  damagedisplay:
    description: DamageDisplay a main command.
    aliases: [dd]
  crston:
    description: Shows developer's discord id.
permissions:
  damagedisplay.skin.*:
    description: Allows access to all skins.
    default: op
  damagedisplay.blacklist:
    description: Allows management of the entity blacklist.
    default: op